### Import

In [13]:
import numpy as np
from scipy.optimize import root_scalar
import math
import datetime
import pandas as pd

### Question 1

In [14]:
pv0 = 100000/(1+0.055*90/365)
pv1 = 100000/(1+0.0548*60/365)
HPR = (pv1/pv0-1)*365/30
print('Holding period yield', HPR)

Holding period yield 0.054905400121643945

ES: This is correct.

### Question 2

In [15]:
coupon = np.array([6.5, 3.25, 4.8, 1.5, 5, 4, 2])
market_price = np.array([101.8137, 97.7066, 101.2414, 89.9751, 103.4012, 99.0074, 87.2087])

In [16]:
def optimize_func(x:float, coupon: float, maturity: int, price: float):
  d = np.arange(start=1, stop=maturity+1)
  sum = np.sum(coupon/np.power(1+x,d))
  sum += 100/((1+x)**maturity)
  return price-sum
y_rate = np.array([])
for i in range(coupon.shape[0]):
  solver = root_scalar(optimize_func, args=(coupon[i], i+1, market_price[i]), bracket=[0.00001,1000])
  y_rate = np.append(y_rate, solver.root)

print('YTM:',y_rate)

YTM: [0.04602819 0.0447422  0.04349691 0.04280008 0.04231033 0.04190526
 0.04142381]

ES: This is correct.

### Question 3

In [17]:
mature_date = datetime.date(2019,9,15)
settlement = datetime.date(2017,3,6)
y = 0.045/2
c = 0.06

P = (100/ (1+ y )**(9/181)) * (c/2 * ( 1+ (1- ((1+y)**(1-6)))/y) + 1 / (1+y)**(6-1))
print('Bond price on 6/3/2017',P)

P2 = (100/ (1+ y )**(2/181)) * (c/2 * ( 0+ (1- ((1+y)**(1-6)))/y) + 1 / (1+y)**(6-1))
print('Bond price on 6/3/2017', P2)

HPR = (P2/P-1)*(365/1)
print('Holding period yield', HPR)

Bond price on 6/3/2017 106.39181406954157
Bond price on 6/3/2017 103.484143338412
Holding period yield -9.975389799901215

ES: This is correct.

### Question 4

In [18]:
mature_date = datetime.date(2019,9,15)
buy_date = datetime.date(2017,3,6)
sell_date = datetime.date(2017,3,7)
y = 0.0445/2
y2 = 0.044/2
c = 0.06

##a)
P1 = (100/ (1+ y )**(9/181)) * (c/2 * ( 1+ (1- ((1+y)**(1-6)))/y) + 1 / (1+y)**(6-1))
P2 = (100/ (1+ y )**(8/181)) * (c/2 * ( 1+ (1- ((1+y)**(1-6)))/y) + 1 / (1+y)**(6-1))
print("HPY:",math.log(P2/P1)*365)

##b)
P3 = (100/ (1+ y2 )**(8/181)) * (c/2 * ( 1+ (1- ((1+y2)**(1-6)))/y2) + 1 / (1+y2)**(6-1))
print("HPY:",math.log(P3/P1)*365)

HPY: 0.0443769021870305
HPY: 0.4581111140024383

ES: Here you calculated the bond prices, but the HPY is missing.

### Question 5

In [19]:
mature_date = datetime.date(2019,9,15)
settlement = datetime.date(2017,3,6)
y = 0.0452
c = 0.06

FV = 3*math.exp(y*(914/365)) + 3*math.exp(y*(730/365)) + 3*math.exp(y*(549/365)) + 3*math.exp(y*(365/365)) + 3*math.exp(y*(184/365)) + 103

HPY = (365/923)*math.log(FV/P)
print(HPY)

0.044495163066464484

ES: This is correct.

### Question 6

In [20]:
98+(19/32) + 2.5*(4*30+8)/180

100.37152777777777

The daycount fractions are not correct: The US Treasury Bonds use the 30/360 convention.

### Question 7

Already shown in class

### Question 8

Reading data

In [21]:
df = pd.read_excel('AustralianGovernmentBonds.xlsx')
df[['coupon', 'maturity']] = df['Coupon and Maturity (click for term sheet)'].str.split(' ', n=1, expand=True)
df.drop(columns=['Coupon and Maturity (click for term sheet)'], inplace=True)
df.drop(columns=['ISIN'], inplace=True)
df.drop(columns=['Outstanding\n(face value, AUD million)'], inplace=True)
df.rename(columns={'Price': 'price'}, inplace=True)
df['coupon'] = df['coupon'].str.rstrip('%').astype(float) /100
df['maturity'] = pd.to_datetime(df['maturity'])
df

     price  coupon   maturity
0    99.78  0.0275 2024-04-21
1    97.31  0.0025 2024-11-21
2    99.19  0.0325 2025-04-21
3    94.18  0.0025 2025-11-21
4   101.02  0.0425 2026-04-21
5    92.32  0.0050 2026-09-21
6   103.02  0.0475 2027-04-21
7    96.59  0.0275 2027-11-21
8    94.21  0.0225 2028-05-21
9    95.68  0.0275 2028-11-21
10   97.48  0.0325 2029-04-21
11   94.40  0.0275 2029-11-21
12   92.30  0.0250 2030-05-21
13   82.50  0.0100 2030-12-21
14   84.27  0.0150 2031-06-21
15   80.01  0.0100 2031-11-21
16   80.41  0.0125 2032-05-21
17   82.78  0.0175 2032-11-21
18  102.82  0.0450 2033-04-21
19   91.12  0.0300 2033-11-21
20   96.87  0.0375 2034-05-21
21   94.32  0.0350 2034-12-21
22   87.31  0.0275 2035-06-21
23   94.17  0.0375 2037-04-21
24   87.88  0.0325 2039-06-21
25   80.13  0.0275 2041-05-21
26   78.82  0.0300 2047-03-21
27   56.92  0.0175 2051-06-21
28  104.43  0.0475 2054-06-21

#### a.

In [22]:
def coupon_payment(current_date: datetime.date, maturity_date: datetime.date, freq: int):
    checkdate = datetime.date(current_date.year+1 if maturity_date.year > current_date.year else current_date.year, maturity_date.month, maturity_date.day)
    n = (maturity_date.year - current_date.year)*freq
    while checkdate > current_date:
        n += 1
        checkdate = datetime.date(checkdate.year if checkdate.month>12/freq else checkdate.year-1, int(checkdate.month-12/freq) if checkdate.month>12/freq else 12 - int(12/freq - checkdate.month), checkdate.day)
    return (n if maturity_date.year == current_date.year else n-2 ,checkdate, datetime.date(checkdate.year if checkdate.month+12/freq < 12 else checkdate.year+1, int(checkdate.month+12/freq) if checkdate.month+12/freq < 12 else int(12/freq + checkdate.month) - 12, checkdate.day))


def optimize_func_config(y:float, coupon: float, price: float, n: int, w: float, freq: int, x: int):
  i = y/freq
  sum = (100/((1+i)**w)) * ((coupon/freq) * (x + (1-(1+i)**(1-n))/i) + 1/((1+i)**(n-1))) 
  return price-sum

y = np.array([])
date = datetime.date(2024, 3, 1)
freq = 2
for i in range(df['coupon'].size):
  n, last_payment, next_payment = coupon_payment(date, df['maturity'][i], freq)
  w = (next_payment-date).days/(next_payment-last_payment).days
  x = 1 if (next_payment-date).days > 7 else 0
  solver = root_scalar(optimize_func_config, args=(df['coupon'][i], df['price'][i], n, w, freq, x), x0=0.039)
  y = np.append(y, solver.root)
df['yield'] = y
df

     price  coupon   maturity     yield
0    99.78  0.0275 2024-04-21  0.117110
1    97.31  0.0025 2024-11-21  0.041660
2    99.19  0.0325 2025-04-21  0.050585
3    94.18  0.0025 2025-11-21  0.038149
4   101.02  0.0425 2026-04-21  0.045017
5    92.32  0.0050 2026-09-21  0.037735
6   103.02  0.0475 2027-04-21  0.042988
7    96.59  0.0275 2027-11-21  0.039659
8    94.21  0.0225 2028-05-21  0.039121
9    95.68  0.0275 2028-11-21  0.039393
10   97.48  0.0325 2029-04-21  0.040523
11   94.40  0.0275 2029-11-21  0.040046
12   92.30  0.0250 2030-05-21  0.040384
13   82.50  0.0100 2030-12-21  0.039947
14   84.27  0.0150 2031-06-21  0.040554
15   80.01  0.0100 2031-11-21  0.040867
16   80.41  0.0125 2032-05-21  0.041346
17   82.78  0.0175 2032-11-21  0.041945
18  102.82  0.0450 2033-04-21  0.043393
19   91.12  0.0300 2033-11-21  0.042282
20   96.87  0.0375 2034-05-21  0.042568
21   94.32  0.0350 2034-12-21  0.042391
22   87.31  0.0275 2035-06-21  0.042335
23   94.17  0.0375 2037-04-21  0.044787
24   87.88  0.0325 2039-06-21  0.044035
25   80.13  0.0275 2041-05-21  0.044817
26   78.82  0.0300 2047-03-21  0.045934
27   56.92  0.0175 2051-06-21  0.045401
28  104.43  0.0475 2054-06-21  0.045355

ES: This is correct.

#### b.

In [23]:
if 'Zero Bond' in df.columns:
    del df['Zero Bond']

def coupon_payment_list(maturity: datetime.date, date: datetime.date, frequency: int):
    coupon_list = []
    checkdate = datetime.date(maturity.year, maturity.month, maturity.day)
    month = int(12/frequency)
    while (checkdate>date):
        coupon_list = [checkdate] + coupon_list
        checkdate = datetime.date( checkdate.year if checkdate.month > month else checkdate.year - 1, checkdate.month - month if checkdate.month > month else 12 + checkdate.month - month, checkdate.day)
    return coupon_list

def interpolation(today: datetime.date, last_date: datetime.date, last_df: float, next_date: datetime.date, next_df: float):
    return math.exp(math.log(last_df) + ((today-last_date).days/(next_date-last_date).days)*(math.log(next_df)-math.log(last_df)))

def interpolate_dates(date: datetime.date, date_array: list):
    greater_dates = date_array[date_array>date]
    next_bond = min(greater_dates, key=lambda x: abs(x - date)) if len(greater_dates)>0 else None
    lower_date = date_array[date_array<date]
    last_bond = min(lower_date, key=lambda x: abs(x - date)) if len(lower_date)>0 else None
    return [date, last_bond, next_bond]

def optimizer(price:float, coupon:float, interpolate: list, bond_price: pd.DataFrame, cb_price: float, today: datetime.date, maturity: datetime.date):
    if isinstance(price, np.ndarray):
        x = price[0]
    else:
        x = price
    factors = []
    for i in interpolate:
        if len(i) == 1:
            check = bond_price[bond_price['maturity']==i[0].strftime('%Y-%m-%d')]['Zero Bond']
            if len(check[check.isna()])==1:
                factors += [x/100]
            else:
                factors += [bond_price[bond_price['maturity']==i[0].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100]
        else:
            if i[2]==None:
                factors += [interpolation(i[0], i[1], bond_price[bond_price['maturity']==i[1].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100, maturity, x/100)]
            elif i[1]==None:
                factors += [interpolation(i[0], today, 1, i[2], bond_price[bond_price['maturity']==i[2].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100)]
            else:
                factors += [interpolation(i[0], i[1], bond_price[bond_price['maturity']==i[1].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100, i[2], bond_price[bond_price['maturity']==i[2].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100)]
    factors = np.array(factors)
    return np.sum(factors*100*coupon) + x - cb_price


df['Zero Bond'] = np.nan
today = datetime.date(2024,3,1)
for i in range(len(df)):
    bond_maturities = df[df['Zero Bond'].isna()==False]['maturity'].dt.date.array
    coupon_dates = coupon_payment_list(df['maturity'].dt.date[i], today, 2)
    interpolate = []
    for j in coupon_dates:
        if j in bond_maturities or len(df[df['maturity']==j.strftime('%Y-%m-%d')])!=0:
            interpolate += [[j]]
        else:
            interpolate += [interpolate_dates(j, bond_maturities)]
    solver = root_scalar(optimizer, args=(df['coupon'][i]/2, interpolate, df[['Zero Bond', 'maturity']], df['price'][i], today, df['maturity'].dt.date[i]), x0=100, method='newton')
    df.at[i, 'Zero Bond'] = solver.root
df.to_excel('Tutorial3_Answer.xlsx', index=False)
df

     price  coupon   maturity     yield  Zero Bond
0    99.78  0.0275 2024-04-21  0.117110  98.426634
1    97.31  0.0025 2024-11-21  0.041660  97.065874
2    99.19  0.0325 2025-04-21  0.050585  94.474846
3    94.18  0.0025 2025-11-21  0.038149  93.700791
4   101.02  0.0425 2026-04-21  0.045017  90.928288
5    92.32  0.0050 2026-09-21  0.037735  90.899640
6   103.02  0.0475 2027-04-21  0.042988  87.515235
7    96.59  0.0275 2027-11-21  0.039659  86.442375
8    94.21  0.0225 2028-05-21  0.039121  84.951692
9    95.68  0.0275 2028-11-21  0.039393  83.220015
10   97.48  0.0325 2029-04-21  0.040523  81.400070
11   94.40  0.0275 2029-11-21  0.040046  79.727759
12   92.30  0.0250 2030-05-21  0.040384  77.986765
13   82.50  0.0100 2030-12-21  0.039947  76.411166
14   84.27  0.0150 2031-06-21  0.040554  74.577418
15   80.01  0.0100 2031-11-21  0.040867  73.161316
16   80.41  0.0125 2032-05-21  0.041346  71.402877
17   82.78  0.0175 2032-11-21  0.041945  69.561365
18  102.82  0.0450 2033-04-21  0.043393  67.223946
19   91.12  0.0300 2033-11-21  0.042282  66.455909
20   96.87  0.0375 2034-05-21  0.042568  64.824428
21   94.32  0.0350 2034-12-21  0.042391  63.404487
22   87.31  0.0275 2035-06-21  0.042335  62.164478
23   94.17  0.0375 2037-04-21  0.044787  55.314308
24   87.88  0.0325 2039-06-21  0.044035  51.014298
25   80.13  0.0275 2041-05-21  0.044817  46.183264
26   78.82  0.0300 2047-03-21  0.045934  34.379672
27   56.92  0.0175 2051-06-21  0.045401  29.099022
28  104.43  0.0475 2054-06-21  0.045355  25.108104

ES: Correct, well done!

#### c.

In [24]:
maturity = datetime.date(2044,2,28)
last_coupon = datetime.date(2043,9,1)
coupon = 0.04
coupon_dates = coupon_payment_list(last_coupon, today, 2)
interpolate = []
bond_maturities = df[df['Zero Bond'].isna()==False]['maturity'].dt.date.array
for j in coupon_dates:
    if j in bond_maturities or len(df[df['maturity']==j.strftime('%Y-%m-%d')])!=0:
        interpolate += [[j]]
    else:
        interpolate += [interpolate_dates(j, bond_maturities)]
interpolate += [interpolate_dates(maturity, bond_maturities)]
bond_price = df[['Zero Bond', 'maturity']]
factors = []
for i in interpolate:
    if len(i) == 1:
        check = bond_price[bond_price['maturity']==i[0].strftime('%Y-%m-%d')]['Zero Bond']
        if len(check[check.isna()])==1:
            factors += [x/100]
        else:
            factors += [bond_price[bond_price['maturity']==i[0].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100]
    else:
        if i[2]==None:
            factors += [interpolation(i[0], i[1], bond_price[bond_price['maturity']==i[1].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100, maturity, x/100)]
        elif i[1]==None:
            factors += [interpolation(i[0], today, 1, i[2], bond_price[bond_price['maturity']==i[2].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100)]
        else:
            factors += [interpolation(i[0], i[1], bond_price[bond_price['maturity']==i[1].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100, i[2], bond_price[bond_price['maturity']==i[2].strftime('%Y-%m-%d')]['Zero Bond'].iloc[0]/100)]
factors = np.array(factors)
last_factor = factors[-1]
factors = factors[:-1]
price = np.sum(factors*coupon*50) + last_factor*100
y = root_scalar(optimize_func_config, args=(coupon, price, 19, 0, 2, 1), x0=0.039).root
print(price, y)

92.33073836817107 0.05368832004612285

ES: There is an error in your code here. The price should be 93.1485426710087

#### d.

In [25]:
def Yield(y,dtn,dpn,c,n,P):
    if dtn <= 7:
        k=0
        
    else:
        k=1
    return (1+y/2)**(-dtn/dpn) * (c*k + c*(1-(1+y/2)**(1-n))/(y/2) + 100*(1+y/2)**(1-n)) - P

In [26]:
# find the AU000XCLWAP3's yield
Bond_Price = 87.88
Coupon = 100 * 3.25/100 / 2
settlement_date = datetime.date(2024,5,1)
next_coupondate = datetime.date(2024,6,21)
dtn = (next_coupondate - today).days
dpn=(datetime.date(2024,12,21)-datetime.date(2024,6,21)).days
coupon_number = round((maturity - next_coupondate).days /dpn + 1)

sol = root_scalar(Yield, bracket=[0.00001,1], args=(dtn,dpn,Coupon,coupon_number,Bond_Price))
Now_yield = sol.root
print(Now_yield)

0.042046782781942904

In [27]:
# find old yield
Old_yield = Now_yield + 0.002
w=dtn/dpn

i=Old_yield/100
k=2 # semi anuually paid
n=coupon_number
c = Coupon
Settlement_Price = (1+i)**(-w) * (c + c*(1-(1+i)**(-5))/i + 100*(1+i)**(-5))
print(Settlement_Price)

109.48981812756173

ES: You misinterpreted 20 bp. 20 bp = 0.20% = 0.002

In [28]:
days = (settlement_date - today).days
HP_Return = (Settlement_Price-Bond_Price)/Bond_Price *365/days
HP_Return

1.4713774402799709